
language: python
python:
  - "3.4"
# command to install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install coverage

env:
  - DB=postgres

efore_script:
  - psql -c "CREATE DATABASE bucketlists;" -U postgres
# command to run tests
script: nosetests --with-coverage --cover-package=bucketlist

after_success:
  - coveralls