
language: python
python:
  - "3.4"
# command to install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install coverage

env:
  - DB=sqlite
# command to run tests
script: --with-coverage --cover-package=bucketlist

after_success:
  - coveralls